import type { BriefDetail, BriefDoc } from "@/lib/brief-types";

import { LABELS_EN } from "./fixtures";

/** The label keys the document layout reads, as the API sends them in English. */
export const DOC_LABELS_EN: Record<string, string> = {
  ...LABELS_EN,
  not_found: "Not found",
  not_found_public: "Not found in public sources.",
  identity: "Which company",
  stat_ownership: "Ownership",
  stat_cloud_network: "Cloud and network",
  lead: "Lead with",
  why_now: "Why this account, why now",
  angle: "Angle",
  evidence: "Evidence",
  alkira_answer: "What Alkira does",
  customer_story: "Customer story",
  proof_point: "Proof point",
  technical_snapshot: "Technical snapshot",
  snap_clouds: "Clouds",
  snap_cloud_connectivity: "Cloud connectivity",
  snap_wan: "WAN",
  snap_firewalls: "Firewalls",
  snap_data_centers: "Data centers",
  snap_plant_networks: "Plant networks",
  who_to_talk_to: "Who to talk to",
  questions: "Questions to ask",
  listen_for: "Listen for",
  alkira_angle: "Alkira angle",
  unconfirmed: "What we couldn't confirm",
  raise_score: "What would raise the score",
  source_second_hand: "second-hand",
  source_last_resort: "last-resort source",
  undated: "source undated",
  source_dated: "source dated {date}",
  open_posting_seen: "open posting, seen {date}",
};

export const DOC: BriefDoc = {
  company: {
    name: "Harbor Fuels",
    legalName: "Harbor Fuels Corporation",
    ticker: "NYSE: HRBR",
    website: "https://www.harborfuels.example",
    identityNote: "Harbor Fuels Corporation of Dallas, not Harbor Fuel Oil of Maine.",
  },
  stats: {
    hq: "Dallas, Texas",
    revenue: "$26,869 million (FY2025)",
    employees: "5,165",
    industry: "Independent energy",
    ownership: "Public",
    cloudNetwork: "Azure with ExpressRoute and Virtual WAN, SD-WAN, Palo Alto firewalls",
  },
  fit: {
    score: 5,
    verdict: "A pending separation plus an open network posting.",
    lead: "Open with the Lubricants separation. Call the network engineering lead in Dallas.",
  },
  angles: [
    {
      title: "Lubricants separation needs its own network",
      useCase: "m_and_a",
      evidence: [
        { text: "Harbor plans to separate Lubricants as a new public company.", date: "2026-07-28", sources: [1] },
        { text: "An open Network Engineer posting covers ExpressRoute and vWAN.", date: "2026-10-06", sources: [2] },
      ],
      alkira: "Alkira runs the Lubricants network as its own segment on a shared fabric.",
      story: {
        id: "michaels",
        customer: "Michaels",
        result: "About 1,400 stores connected to Google Cloud in three weeks.",
      },
      dealDate: "2026-07-28",
      dealStatus: "pending",
      dealPendingQuote: "The transaction is intended to be executed over the next 12-18 months.",
    },
    {
      title: "China and global systems joined by a dedicated line",
      useCase: "china_global",
      evidence: [{ text: "Core ERP runs in the AWS China region.", date: "", sources: [3] }],
      alkira: "Alkira links both sides through one backbone.",
      story: { id: "metric", customer: "", result: "Network provisioning speed improvement: 80%." },
      dealDate: "",
      dealStatus: "none",
      dealPendingQuote: "",
    },
  ],
  snapshot: {
    clouds: { text: "Azure, with AWS or GCP exposure preferred", sources: [2] },
    cloudConnectivity: { text: "ExpressRoute, VPN, Azure Virtual WAN hub-and-spoke, BGP", sources: [2] },
    wan: { text: "SD-WAN across data center, campus and branch networks", sources: [2] },
    firewalls: { text: "", sources: [] },
    dataCenters: { text: "Hybrid environments across on-premises data center and cloud", sources: [2] },
    plantNetworks: { text: "", sources: [] },
  },
  people: [
    { name: "Dana Reyes", role: "Chief Information Officer", note: "Quoted in the release.", sources: [1] },
    { name: "", role: "Network engineering lead, Dallas", note: "", sources: [] },
  ],
  questions: [
    {
      question: "Which sites need their own connectivity first?",
      listenFor: "Shared services and a target date.",
      alkiraAngle: "Each side runs as a separate segment until cutover.",
      angle: 1,
    },
    {
      question: "How long does a new Azure hub take to build today?",
      listenFor: "Hand-built hubs and weeks of lead time.",
      alkiraAngle: "A new region connects as a design change.",
      angle: 0,
    },
  ],
  unconfirmed: ["Which Azure regions connect today.", "Whether SD-WAN is deployed."],
  raiseScore: ["A named IT leader confirming the separation scope."],
  format: 2,
  version: 4,
  language: "en",
  generated: "2026-10-06",
  references: [
    {
      n: 1,
      title: "Harbor Fuels press release: separation of Lubricants",
      url: "https://www.harborfuels.example/press/2026/separation",
      date: "2026-07-28",
      sourceType: "first_hand",
      openPosting: false,
    },
    {
      n: 2,
      title: "Harbor Fuels careers: Network Engineer (open posting, seen 2026-10-06)",
      url: "https://careers.harborfuels.example/job/network-engineer",
      date: "2026-10-06",
      sourceType: "first_hand",
      openPosting: true,
    },
    {
      n: 3,
      title: "Trade press on the ERP move",
      url: "https://news.example/harbor-erp",
      date: "",
      sourceType: "second_hand",
      openPosting: false,
    },
  ],
  research: { searches: 13, pages: 10, seconds: 79, stoppedBy: "finished" },
};

/** A response that carries the document beside the legacy fields, as the API sends it. */
export const DOC_BRIEF: BriefDetail = {
  id: "b-doc",
  company: "Harbor Fuels",
  statsLine: "HQ: Dallas, Texas | Revenue: $26.9B (FY2025) | Employees: 5,165 | Ownership: Public (NYSE: HRBR)",
  score: 5,
  scoreRationale: "A pending separation plus an open network posting. Open with the Lubricants separation.",
  infra: {
    cloudPlatforms: "Azure, with AWS or GCP exposure preferred.",
    onPrem: "Hybrid environments across on-premises data center and cloud.",
    deployment: "ExpressRoute, VPN, Azure Virtual WAN hub-and-spoke, BGP.",
    complexity: "SD-WAN across data center, campus and branch networks.",
  },
  signals: ["Harbor plans to separate Lubricants as a new public company (source dated 28 Jul 2026)."],
  entryPoints: [
    {
      heading: "Lubricants separation needs its own network",
      signal: "An open Network Engineer posting covers ExpressRoute and vWAN.",
      solution: "Alkira runs the Lubricants network as its own segment on a shared fabric.",
      proof: "Michaels: About 1,400 stores connected to Google Cloud in three weeks.",
    },
  ],
  startersMd: '1. "Which sites need their own connectivity first?"',
  referencesMd: "[1] Harbor Fuels press release — https://www.harborfuels.example/press/2026/separation",
  language: "en",
  labels: DOC_LABELS_EN,
  createdAt: "2026-10-06T03:27:19+00:00",
  format: 2,
  doc: DOC,
};
